

trigger:
- master

resources:
- repo: self

variables:
  imageRepo: kubernetsapp
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerC'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/server/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/manifests'
        artifact: 'manifests'
        publishLocation: 'pipeline'
- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
   acsercret: k8sexamplesacrauth
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: 'k8dev.default'
    pool: 
       vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
  
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          - task: KubernetesManifest@0
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: 'kubernetsAKS'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: '$(acsercret)'
              dockerRegistryEndpoint: 'DockerC'
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'kubernetsAKS'
              namespace: 'default'
              manifests: |
                  $(Pipeline.Workspace)/deployment.yml
                  $(Pipeline.Workspace)/service.yml



