apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubernetsapp"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubernetsapp"
  template:
    metadata:
      labels:
        app: "kubernetsapp"
    spec:
      containers:
        - name: "kubernetsapp"
          image: "kubernetsto.azurecr.io/kubernetsapp"
          imagePullPolicy: Always
          ports:
          - containerPort: 80