apiVersion: v1
kind: Service
metadata:
    name: "kubernetsto-9f51"
    labels:
        app: "kubernetsto-9f51"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubernetsto-9f51"