on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainerregistryto.azurecr.io
        username: ${{ secrets.acr_mycontainerregistryto_username }}
        password: ${{ secrets.acr_mycontainerregistryto_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/server" -f  "server/Dockerfile" -t mycontainerregistryto.azurecr.io/kubernetsto:${{ github.sha }} --label dockerfile-path=server/Dockerfile
        docker push mycontainerregistryto.azurecr.io/kubernetsto:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernetsto_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernetstoa952 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernetstoa952`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernetstoa952
        container-registry-url: mycontainerregistryto.azurecr.io
        container-registry-username: ${{ secrets.acr_mycontainerregistryto_username }}
        container-registry-password: ${{ secrets.acr_mycontainerregistryto_password }}
        secret-name: kubernetstodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubernetstoa952
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          mycontainerregistryto.azurecr.io/kubernetsto:${{ github.sha }}
        imagepullsecrets: |
          kubernetstodockerauth
